name: yt-dlp-api
services:
  - name: api
    type: web
    build:
      type: docker
      dockerfile: ./Dockerfile
    ports:
      - port: 8000
        protocol: http
    env:
      - PORT=8000
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    health_check:
      http:
        path: /health
        port: 8000
      initial_delay_seconds: 30
      timeout_seconds: 10
      period_seconds: 30
      success_threshold: 1
      failure_threshold: 3
    scaling:
      min: 1
      max: 3
    instance_type: nano
    regions:
      - fra
      - was
      - sin